AWSTemplateFormatVersion: '2010-09-09'
Description: Static infrastructure for TICF Query results
Transform: AWS::Serverless-2016-10-31

Parameters:
  Environment:
    Description: The environment type
    Type: String
    AllowedValues:
      - dev
      - build
      - staging
      - integration
      - production

Resources:
  QueryResultsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      BucketName: !Sub ${AWS::StackName}-${Environment}-query-results-bucket
      LifecycleConfiguration:
        Rules:
          - Id: AnalysisCleanupRule
            Status: Enabled
            ExpirationInDays: 30
      LoggingConfiguration:
        DestinationBucketName: !Ref QueryResultsLogsBucket
        LogFilePrefix: String
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled

  QueryResultsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref QueryResultsBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowSSLRequestsOnly
            Action: s3:*
            Effect: Deny
            Resource:
              - !Sub ${QueryResultsBucket.Arn}/*
            Principal: '*'
            Condition:
              Bool:
                aws:SecureTransport: false
          - Sid: AthenaLambdaAccess
            Action:
              - s3:GetBucketLocation
              - s3:GetObject
              - s3:ListBucket
              - s3:ListBucketMultipartUploads
              - s3:ListMultipartUploadParts
              - s3:AbortMultipartUpload
              - s3:PutObject
            Effect: Allow
            Resource:
              - '{{resolve:ssm:QueryResultsBucketArn}}'
              - '{{resolve:ssm:QueryResultsBucketArn}}/*'
            Principal:
              AWS:
                - '{{resolve:ssm:AuditAccountRootArn}}'
            Condition:
              StringLike:
                aws:PrincipalArn: 'arn:aws:iam::*:role/txma-ticf-integration-InitiateAthenaQueryFunctionR-*'

  QueryResultsLogsBucket:
    #checkov:skip=CKV_AWS_18:This is the query results logs bucket
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AWS::StackName}-${Environment}-query-results-logs
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled

  SecureFraudSiteDataTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${AWS::StackName}-secure-fraud-site-data
      AttributeDefinitions:
        - AttributeName: downloadHash
          AttributeType: S
        - AttributeName: zendeskId
          AttributeType: S
      KeySchema:
        - AttributeName: downloadHash
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: zendeskIdAndDownloadHashIndex
          KeySchema:
            - AttributeName: zendeskId
              KeyType: HASH
          Projection:
            ProjectionType: 'KEYS_ONLY'
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      SSESpecification:
        SSEEnabled: true
        SSEType: KMS
        KMSMasterKeyId: '{{resolve:ssm:DatabaseKmsKeyArn}}'

  SecureFraudApiWafAcl:
    Type: AWS::WAFv2::WebACL
    Properties:
      DefaultAction:
        Allow: {}
      Scope: REGIONAL
      VisibilityConfig:
        CloudWatchMetricsEnabled: true
        MetricName: SecureFraudApiWafMetric
        SampledRequestsEnabled: true
      Rules:
        - Name: AwsManagedRulesCommonRuleSet
          Priority: 0
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesCommonRuleSet
              ExcludedRules: []
          OverrideAction:
            Count: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: SecureFraudApiCommonRuleSetMetric
        - Name: AWSManagedRulesKnownBadInputsRuleSet
          Priority: 1
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesKnownBadInputsRuleSet
          OverrideAction:
            None: {}
          VisibilityConfig:
            CloudWatchMetricsEnabled: true
            MetricName: SecureFraudApiKnownBadInputsRuleSetMetric
            SampledRequestsEnabled: true
        - Name: AWSManagedRulesAmazonIpReputationList
          Priority: 2
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesAmazonIpReputationList
          OverrideAction:
            None: {}
          VisibilityConfig:
            CloudWatchMetricsEnabled: true
            MetricName: SecureFraudApiIpReputationListMetric
            SampledRequestsEnabled: true

  # Need a separate KMS key here for the audit queue because we need to grant access to the event processing account
  # and our main KMS key definitions are in 'core', which is a shared set of definitions across all stacks.
  AuditDataRequestEventsQueueKmsKey:
    Type: AWS::KMS::Key
    Properties:
      EnableKeyRotation: true
      KeyPolicy:
        Version: '2012-10-17'
        Statement:
          - Sid: Enable Root access
            Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
            Action:
              - kms:*
            Resource: '*'
          - Sid: Enable Decrypt access for Event Processing
            Effect: Allow
            Principal:
              AWS: !Sub '{{ssm:resolve:EventProcessingAccountRootArn}}'
            Action:
              - kms:Decrypt
            Resource: '*'
          - Sid: Allow AWS Lambda access
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action:
              - kms:GenerateDataKey
              - kms:Encrypt
              - kms:Decrypt
            Resource: '*'

  AuditDataRequestEventsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub ${AWS::StackName}-${Environment}-audit-data-request-events-queue
      KmsMasterKeyId: !GetAtt AuditDataRequestEventsQueueKmsKey.Arn
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt AuditDataRequestEventsDeadLetterQueue.Arn
        maxReceiveCount: 5

  AuditDataRequestEventsDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub ${AWS::StackName}-${Environment}-audit-data-request-events-dead-letter-queue
      KmsMasterKeyId: !GetAtt AuditDataRequestEventsQueueKmsKey.Arn

  AuditDataRequestQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref AuditDataRequestEventsQueue
      PolicyDocument:
        Statement:
          - Sid: AllowEventProcessingAccountQueueRead
            Action:
              - 'sqs:ChangeMessageVisibility'
              - 'sqs:DeleteMessage'
              - 'sqs:GetQueueAttributes'
              - 'sqs:ReceiveMessage'
            Effect: 'Allow'
            Resource: !GetAtt AuditDataRequestEventsQueue.Arn
            Principal:
              AWS:
                - '{{resolve:ssm:EventProcessingAccountNumber}}'

  QueryResultsBucketArnParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: QueryResultsBucketArn
      Type: String
      Value: !GetAtt QueryResultsBucket.Arn

  QueryResultsBucketNameParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: QueryResultsBucketName
      Type: String
      Value: !Ref QueryResultsBucket

  SecureFraudSiteDataTableArnParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: SecureFraudSiteDataTableArn
      Type: String
      Value: !GetAtt SecureFraudSiteDataTable.Arn

  SecureFraudSiteDataTableNameParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: SecureFraudSiteDataTableName
      Type: String
      Value: !Ref SecureFraudSiteDataTable

  SecureFraudApiWafAclArnParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: SecureFraudApiWafAclArn
      Type: String
      Value: !GetAtt SecureFraudApiWafAcl.Arn

  AuditDataRequestEventsQueueArnParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: AuditDataRequestEventsQueueArn
      Type: String
      Value: !GetAtt AuditDataRequestEventsQueue.Arn

  AuditDataRequestEventsQueueUrlParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: AuditDataRequestEventsQueueUrl
      Type: String
      Value: !Ref AuditDataRequestEventsQueue

  AuditDataRequestEventsQueueKmsKeyArnParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: AuditDataRequestEventsQueueKmsKeyArn
      Type: String
      Value: !GetAtt AuditDataRequestEventsQueueKmsKey.Arn

Outputs:
  QueryResultsBucketName:
    Value: !Ref QueryResultsBucket
    Export:
      Name: QueryResultsBucketName
