AWSTemplateFormatVersion: '2010-09-09'
Description: Static infrastructure for TICF Query results
Transform: AWS::Serverless-2016-10-31

Parameters:
  Environment:
    Description: The environment type
    Type: String
    AllowedValues:
      - dev
      - build
      - staging
      - integration
      - production

Resources:
  QueryResultsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      BucketName: !Sub ${AWS::StackName}-${Environment}-query-results-bucket
      LifecycleConfiguration:
        Rules:
          - Id: AnalysisCleanupRule
            Status: Enabled
            ExpirationInDays: 30
      LoggingConfiguration:
        DestinationBucketName: !Ref QueryResultsLogsBucket
        LogFilePrefix: String
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled

  QueryResultsLogsBucket:
    #checkov:skip=CKV_AWS_18:This is the query results logs bucket
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AWS::StackName}-${Environment}-query-results-logs
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled

  SecureFraudSiteDataTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${AWS::StackName}-secure-fraud-site-data
      AttributeDefinitions:
        - AttributeName: downloadHash
          AttributeType: S
        - AttributeName: zendeskId
          AttributeType: S
      KeySchema:
        - AttributeName: downloadHash
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: zendeskIdAndDownloadHashIndex
          KeySchema:
            - AttributeName: zendeskId
              KeyType: HASH
          Projection:
            ProjectionType: 'KEYS_ONLY'
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      SSESpecification:
        SSEEnabled: true
        SSEType: KMS
        KMSMasterKeyId: '{{resolve:ssm:DatabaseKmsKeyArn}}'

  QueryResultsBucketArnParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: QueryResultsBucketArn
      Type: String
      Value: !GetAtt QueryResultsBucket.Arn

  QueryResultsBucketNameParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: QueryResultsBucketName
      Type: String
      Value: !Ref QueryResultsBucket

  SecureFraudSiteDataTableArnParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: SecureFraudSiteDataTableArn
      Type: String
      Value: !GetAtt SecureFraudSiteDataTable.Arn

  SecureFraudSiteDataTableNameParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: SecureFraudSiteDataTableName
      Type: String
      Value: !Ref SecureFraudSiteDataTable

Outputs:
  QueryResultsBucketName:
    Value: !Ref QueryResultsBucket
    Export:
      Name: QueryResultsBucketName
