AWSTemplateFormatVersion: '2010-09-09'
Description: Developer tool infrastructure
Transform: AWS::Serverless-2016-10-31

Parameters:
  CodeSigningConfigArn:
    Description: The ARN of the Code Signing Config to use, provided by the deployment pipeline
    Type: String
    Default: none
  Environment:
    Description: The environment type
    Type: String
    AllowedValues:
      - dev
      - build
      - staging
  PermissionsBoundary:
    Description: The ARN of the permissions boundary to apply to any role created by the template
    Type: String
    Default: none

Conditions:
  FeatureBranches: !Equals [!Ref Environment, dev]
  UseCodeSigning: !Not [!Equals [!Ref CodeSigningConfigArn, none]]
  UsePermissionsBoundary: !Not [!Equals [!Ref PermissionsBoundary, none]]

Globals:
  Function:
    CodeSigningConfigArn:
      !If [UseCodeSigning, !Ref CodeSigningConfigArn, !Ref AWS::NoValue]
    CodeUri: dist/
    Environment:
      Variables:
        NODE_OPTIONS: --enable-source-maps
    PermissionsBoundary:
      !If [UsePermissionsBoundary, !Ref PermissionsBoundary, !Ref AWS::NoValue]
    ReservedConcurrentExecutions: 10
    Runtime: nodejs16.x
    Timeout: 30

Resources:
  EmptyS3BucketsFunction:
    #checkov:skip=CKV_AWS_115:Defined in Globals
    #checkov:skip=CKV_AWS_116:DLQ not required as failures will be reported to CloudFormation
    #checkov:skip=CKV_AWS_117:VPC not required
    Condition: FeatureBranches
    Type: AWS::Serverless::Function
    Properties:
      Handler: emptyS3Buckets.handler
      FunctionName: !Sub ${AWS::StackName}-empty-s3-buckets
      KmsKeyArn: '{{resolve:ssm:LambdaKmsKeyArn}}'
      Policies:
        - Statement:
            - Sid: CloudFormationListResources
              Effect: Allow
              Action:
                - cloudformation:ListStackResources
              Resource: '*'
            - Sid: Logs
              Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: !GetAtt EmptyS3BucketsLogs.Arn
            - Sid: S3Permissions
              Effect: Allow
              Action:
                - s3:DeleteObject*
                - s3:GetBucketVersioning
                - s3:ListBucket
                - s3:ListBucketVersions
                - s3:PutBucketVersioning
              Resource: '*'

  DynamoOperationsFunction:
    #checkov:skip=CKV_AWS_115:Defined in Globals
    #checkov:skip=CKV_AWS_116:DLQ not required as failures will be reported to CloudFormation
    #checkov:skip=CKV_AWS_117:VPC not required
    Type: AWS::Serverless::Function
    Properties:
      Handler: dynamoOperations.handler
      Environment:
        Variables:
          QUERY_REQUEST_DYNAMODB_TABLE_NAME: '{{resolve:ssm:QueryRequestTableName}}'
      FunctionName: !Sub ${AWS::StackName}-dynamo-operations
      KmsKeyArn: '{{resolve:ssm:LambdaKmsKeyArn}}'
      Policies:
        - Statement:
            - Sid: DecryptKmsKeys
              Effect: Allow
              Action:
                - kms:Decrypt
              Resource:
                - '{{resolve:ssm:DatabaseKmsKeyArn}}'
            - Sid: QueryRequestTableReadWrite
              Effect: Allow
              Action:
                - dynamodb:PutItem
                - dynamodb:GetItem
                - dynamodb:DeleteItem
              Resource: '{{resolve:ssm:QueryRequestTableArn}}'

  EmptyS3BucketsLogs:
    Condition: FeatureBranches
    Type: AWS::Logs::LogGroup
    Properties:
      KmsKeyId: '{{resolve:ssm:LogsKmsKeyArn}}'
      LogGroupName: !Sub '/aws/lambda/${AWS::StackName}-empty-s3-buckets'
      RetentionInDays: 30

  IntegrationTestDataBucket:
    #checkov:skip=CKV_AWS_18: Logging not required for test resource
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      BucketName: !Sub ${AWS::StackName}-${Environment}-test-data-bucket
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled

  EmptyS3BucketsFunctionArnParameter:
    Condition: FeatureBranches
    Type: AWS::SSM::Parameter
    Properties:
      Name: EmptyS3BucketsFunctionArn
      Type: String
      Value: !GetAtt EmptyS3BucketsFunction.Arn

  IntegrationTestDataBucketNameParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: IntegrationTestDataBucketName
      Type: String
      Value: !Ref IntegrationTestDataBucket
