AWSTemplateFormatVersion: '2010-09-09'
Description: Creates the necessary DNS zones and records for the query results account
Parameters:
  Environment:
    Description: The environment type
    Type: String
    AllowedValues:
      - build
      - staging
      - integration
      - production

Mappings:
  Environment:
    build:
      ResultsApiDomainName: results.transaction.build.account.gov.uk
    staging:
      ResultsApiDomainName: results.transaction.staging.account.gov.uk
    integration:
      ResultsApiDomainName: results.transaction.integration.account.gov.uk
    production:
      ResultsApiDomainName: results.transaction.account.gov.uk

Resources:
  ResultsApiPublicHostedZone:
    Type: AWS::Route53::HostedZone
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      Name: !FindInMap [Environment, !Ref Environment, ResultsApiDomainName]

  ResultsApiCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName:
        !FindInMap [Environment, !Ref Environment, ResultsApiDomainName]
      DomainValidationOptions:
        - DomainName:
            !FindInMap [Environment, !Ref Environment, ResultsApiDomainName]
          HostedZoneId: !Ref ResultsApiPublicHostedZone
      ValidationMethod: DNS

  ResultsApiDomainName:
    Type: AWS::ApiGateway::DomainName
    Properties:
      DomainName:
        !FindInMap [Environment, !Ref Environment, ResultsApiDomainName]
      EndpointConfiguration:
        Types:
          - REGIONAL
      RegionalCertificateArn: !Ref ResultsApiCertificate
      SecurityPolicy: TLS_1_2

  ResultsApiDomainNameParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: ResultsApiDomainName
      Type: String
      Value: !Ref ResultsApiDomainName

Outputs:
  ResultsApiPublicHostedZoneNameServers:
    Value: !Join [',', !GetAtt ResultsPublicApiHostedZone.NameServers]
