name: Package data-analysis-config infrastructure

on:
  pull_request:
    branches:
      - main
    paths:
      - data-analysis-config/**
  push:
    branches:
      - main
    paths:
      - data-analysis-config/**
  workflow_dispatch: {}

env:
  AWS_REGION: eu-west-2

jobs:
  validate:
    name: Validate template
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: data-analysis-config
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'
      - name: Setup SAM CLI
        uses: aws-actions/setup-sam@v2
      - name: Assume AWS Validate role
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.GH_ACTIONS_VALIDATE_ROLE_ARN_DATA_ANALYSIS_CONFIG }}
      - name: Validate SAM template
        if: always()
        run: sam validate
      - name: Run Checkov on SAM template
        if: always()
        uses: bridgecrewio/checkov-action@master
        with:
          file: template.yaml
          quiet: true
          framework: cloudformation
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: data-analysis-config-sam-template
          path: |
            data-analysis-config/template.yaml

  package:
    strategy:
      matrix:
        target: [AUDIT_DEV, AUDIT_BUILD]
        include:
          - target: AUDIT_DEV
            ARTIFACT_BUCKET_NAME_SECRET: ARTIFACT_BUCKET_NAME_DATA_ANALYSIS_CONFIG_AUDIT_DEV
            GH_ACTIONS_ROLE_ARN_SECRET: GH_ACTIONS_ROLE_ARN_DATA_ANALYSIS_CONFIG_AUDIT_DEV
          - target: AUDIT_BUILD
            ARTIFACT_BUCKET_NAME_SECRET: ARTIFACT_BUCKET_NAME_DATA_ANALYSIS_CONFIG_AUDIT_BUILD
            GH_ACTIONS_ROLE_ARN_SECRET: GH_ACTIONS_ROLE_ARN_DATA_ANALYSIS_CONFIG_AUDIT_BUILD
    name: Package template
    if: (github.event_name == 'push' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main'
    needs: [validate]
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: data-analysis-config-sam-template
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'
      - name: Setup SAM CLI
        uses: aws-actions/setup-sam@v2
      - name: Assume AWS role
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets[matrix.GH_ACTIONS_ROLE_ARN_SECRET] }}
      - name: Package SAM app
        uses: alphagov/di-devplatform-upload-action@v2
        with:
          artifact-bucket-name: ${{ secrets[matrix.ARTIFACT_BUCKET_NAME_SECRET] }}
          signing-profile-name: ${{ secrets.SIGNING_PROFILE_NAME }}
          working-directory: '.'
