name: Package dns zones

on:
  push:
    branches:
      - main
    paths:
      - "dns-zones/**"
  workflow_dispatch: {}

env:
  AWS_REGION: eu-west-2

jobs:
  validate:
    name: Validate template
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'
      - name: Setup SAM CLI
        uses: aws-actions/setup-sam@v2
      - name: Assume AWS Validate role
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.GH_ACTIONS_VALIDATE_ROLE_ARN_DNS_ZONES }}
      - name: Validate SAM template
        if: always()
        run: sam validate -t dns-zones/template.yaml
      - name: Run Checkov on SAM template
        if: always()
        uses: bridgecrewio/checkov-action@master
        with:
          file: dns-zones/template.yaml
          quiet: true
          framework: cloudformation
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: dns-zones-sam-template
          path: |
            dns-zones/template.yaml
  package:
    name: Package template
    needs: [validate]
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: dns-zones-sam-template
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'
      - name: Setup SAM CLI
        uses: aws-actions/setup-sam@v2
      - name: Assume AWS role
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.GH_ACTIONS_ROLE_ARN_DNS_ZONES }}
      - name: Package SAM app
        uses: alphagov/di-devplatform-upload-action@v2
        with:
          artifact-bucket-name: ${{ secrets.ARTIFACT_BUCKET_NAME_DNS_ZONES }}
          signing-profile-name: ${{ secrets.SIGNING_PROFILE_NAME }}
          working-directory: '.'
